import { ConfigOptions } from "./types"
import {
  OperationCollection,
  transformToHandlerCode,
  transformToGenerateResultFunctions,
} from "./transform"

const getImportsCode = () => {
  const imports = [`import { HttpResponse, http } from 'msw';`]

  return imports.join("\n")
}

export const mockTemplate = (
  operationCollection: OperationCollection,
  baseURL: string,
  options: ConfigOptions,
) => `/**
* This file is AUTO GENERATED by [@swarmica/msw-auto-mock](https://github.com/Swarmica/msw-auto-mock)
* Don't edit this file.
*/
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
${getImportsCode()}

const baseURL = '${baseURL}';

export const handlers = [
  ${transformToHandlerCode(operationCollection, options)}
];

${transformToGenerateResultFunctions(operationCollection, baseURL)}
`

export const nodeIntegration = [
  `import { setupServer } from 'msw/node'`,
  `import { handlers } from './handlers'`,
  `export const server = setupServer(...handlers)`,
].join(`\n`)
